# Generated by Django 5.2 on 2025-05-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
